import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap-icons/font/bootstrap-icons.css";
import "./globals.css";
import Home from "./pages/Home";

// import { LoginView } from "./pages/Login"
// import { PainelControle } from "./pages/PainelControle"
// import { CadastroView } from "./pages/Cadastro"
// import { Sidebar } from "./components/Menu"
// import UsuariosCadastrados from "./pages/UsuariosCadastrado";

const inter = Inter({
  variable: "--font-primary",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MVP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${inter.variable} container`}>
        {children}
      </body>
    </html>
  );
}
